# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BeamRangeproofData(p.MessageType):
    MESSAGE_WIRE_TYPE = 713

    def __init__(
        self,
        data: bytes = None,
        is_public: bool = None,
    ) -> None:
        self.data = data
        self.is_public = is_public

    @classmethod
    def get_fields(cls):
        return {
            1: ('data', p.BytesType, 0),
            2: ('is_public', p.BoolType, 0),
        }
