# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .BeamKeyIDV import BeamKeyIDV


class BeamGenerateRangeproof(p.MessageType):
    MESSAGE_WIRE_TYPE = 712

    def __init__(
        self,
        kidv: BeamKeyIDV = None,
        slot: int = None,
        is_public: bool = None,
    ) -> None:
        self.kidv = kidv
        self.slot = slot
        self.is_public = is_public

    @classmethod
    def get_fields(cls):
        return {
            1: ('kidv', BeamKeyIDV, 0),
            2: ('slot', p.UVarintType, 0),
            3: ('is_public', p.BoolType, 0),
        }
