# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .BeamSignature import BeamSignature


class BeamVerifyMessage(p.MessageType):
    MESSAGE_WIRE_TYPE = 704

    def __init__(
        self,
        signature: BeamSignature = None,
        xpub: bytes = None,
        message: bytes = None,
    ) -> None:
        self.signature = signature
        self.xpub = xpub
        self.message = message

    @classmethod
    def get_fields(cls):
        return {
            1: ('signature', BeamSignature, 0),
            2: ('xpub', p.BytesType, 0),
            3: ('message', p.BytesType, 0),
        }
