# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .BeamECCPoint import BeamECCPoint


class BeamSignature(p.MessageType):
    MESSAGE_WIRE_TYPE = 703

    def __init__(
        self,
        nonce_pub: BeamECCPoint = None,
        sign_k: bytes = None,
    ) -> None:
        self.nonce_pub = nonce_pub
        self.sign_k = sign_k

    @classmethod
    def get_fields(cls):
        return {
            1: ('nonce_pub', BeamECCPoint, 0),
            2: ('sign_k', p.BytesType, 0),
        }
