# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .BeamKeyIDV import BeamKeyIDV


class BeamGenerateKey(p.MessageType):
    MESSAGE_WIRE_TYPE = 709

    def __init__(
        self,
        kidv: BeamKeyIDV = None,
        is_coin_key: bool = None,
    ) -> None:
        self.kidv = kidv
        self.is_coin_key = is_coin_key

    @classmethod
    def get_fields(cls):
        return {
            1: ('kidv', BeamKeyIDV, 0),
            2: ('is_coin_key', p.BoolType, 0),
        }
