# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BeamConfirmResponseMessage(p.MessageType):
    MESSAGE_WIRE_TYPE = 701

    def __init__(
        self,
        text: str = None,
        response: bool = None,
    ) -> None:
        self.text = text
        self.response = response

    @classmethod
    def get_fields(cls):
        return {
            1: ('text', p.UnicodeType, 0),
            2: ('response', p.BoolType, 0),
        }
