# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BeamOwnerKey(p.MessageType):
    MESSAGE_WIRE_TYPE = 708

    def __init__(
        self,
        key: bytes = None,
    ) -> None:
        self.key = key

    @classmethod
    def get_fields(cls):
        return {
            1: ('key', p.BytesType, 0),
        }
