# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BeamPublicKey(p.MessageType):
    MESSAGE_WIRE_TYPE = 706

    def __init__(
        self,
        pub_x: bytes = None,
        pub_y: bytes = None,
    ) -> None:
        self.pub_x = pub_x
        self.pub_y = pub_y

    @classmethod
    def get_fields(cls):
        return {
            1: ('pub_x', p.BytesType, 0),
            2: ('pub_y', p.BytesType, 0),
        }
