# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BeamDisplayMessage(p.MessageType):
    MESSAGE_WIRE_TYPE = 700

    def __init__(
        self,
        text: str = None,
        show_display: bool = None,
    ) -> None:
        self.text = text
        self.show_display = show_display

    @classmethod
    def get_fields(cls):
        return {
            1: ('text', p.UnicodeType, 0),
            2: ('show_display', p.BoolType, 0),
        }
