# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BeamECCImage(p.MessageType):
    MESSAGE_WIRE_TYPE = 711

    def __init__(
        self,
        image_x: bytes = None,
    ) -> None:
        self.image_x = image_x

    @classmethod
    def get_fields(cls):
        return {
            1: ('image_x', p.BytesType, 0),
        }
