# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BeamPublicKey(p.MessageType):
    MESSAGE_WIRE_TYPE = 706

    def __init__(
        self,
        xpub: bytes = None,
    ) -> None:
        self.xpub = xpub

    @classmethod
    def get_fields(cls):
        return {
            1: ('xpub', p.BytesType, 0),
        }
