# Automatically generated by pb2py
# fmt: off
import protobuf as p


class BeamGetOwnerKey(p.MessageType):
    MESSAGE_WIRE_TYPE = 707

    def __init__(
        self,
        show_display: bool = None,
    ) -> None:
        self.show_display = show_display

    @classmethod
    def get_fields(cls):
        return {
            1: ('show_display', p.BoolType, 0),
        }
